name: Feature Collection
on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:

jobs:
  collect-features:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install openmeteo_requests requests_cache retry_requests pandas
        pip freeze > requirements.txt  # Optional: Create requirements file
        
    - name: Run feature collection
      run: python scripts/collect_features.py
      
    - name: Upload features
      uses: actions/upload-artifact@v4
      with:
        name: aqi-features
        path: data/hourly_features.csv
