name: Model Training
on:
  schedule:
    - cron: '30 0 * * *'  # Daily at 00:30 UTC
  workflow_dispatch:

jobs:
  # Independent job that runs if features collection fails
  check-features:
    runs-on: ubuntu-latest
    outputs:
      features_available: ${{ steps.check.outputs.exists }}
    steps:
      - name: Check for features
        id: check
        run: |
          echo "exists=true" >> $GITHUB_OUTPUT
          # Or use API to verify last successful features run
          # echo "exists=${{ github.event_name == 'workflow_dispatch' || fromJson('true') }}" >> $GITHUB_OUTPUT

  # Main training job
  train-model:
    runs-on: ubuntu-latest
    needs: check-features  # Soft dependency
    if: needs.check-features.outputs.features_available == 'true'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download latest features
      uses: actions/download-artifact@v4
      with:
        name: aqi-features-*
        path: data/
        pattern: aqi-features-*
        merge-multiple: true
        
    - name: Verify download
      run: |
        [ -f data/hourly_features.csv ] || exit 1
        echo "Download verification passed"
        
    - name: Train model
      run: python scripts/train_model.py
      
    - name: Save model
      uses: actions/upload-artifact@v4
      with:
        name: aqi-model-${{ github.run_number }}
        path: models/
        retention-days: 30
