name: Model Training
on:
  schedule:
    - cron: '30 * * * *'  # Runs at :30 past every hour
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      actions: read
      contents: read

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install xgboost scikit-learn pandas numpy joblib
        pip list
        
    - name: Download latest features
      uses: actions/download-artifact@v4
      with:
        name: aqi-features
        path: data/
        
    - name: Fallback download (if exact name fails)
      if: failure() && steps.download-features.conclusion == 'failure'
      uses: actions/download-artifact@v4
      with:
        name: aqi-features-*
        path: data/
        pattern: aqi-features-*
        merge-multiple: true
        
    - name: Verify features
      run: |
        import pandas as pd
        try:
            df = pd.read_csv('data/hourly_features.csv')
            print(f"Successfully loaded {len(df)} records")
        except Exception as e:
            print(f"::error::Failed to load features: {str(e)}")
            exit(1)
      shell: python
        
    - name: Create models directory
      run: mkdir -p models
      
    - name: Train model
      run: python scripts/train_model.py
      
    - name: Verify model
      run: |
        import xgboost, os
        if not os.path.exists('models/aqi_model.json'):
            print("::error::Model file not found!")
            exit(1)
        try:
            model = xgboost.Booster()
            model.load_model('models/aqi_model.json')
            print("Model verified successfully")
        except Exception as e:
            print(f"::error::Model verification failed: {str(e)}")
            exit(1)
      shell: python
        
    - name: Upload model
      uses: actions/upload-artifact@v4
      with:
        name: aqi-model-${{ github.run_number }}
        path: models/
        retention-days: 7
