name: Model Training
on:
  schedule:
    - cron: '30 * * * *'  # Runs at :30 past every hour
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      actions: read
    
    steps:
    - uses: actions/checkout@v4
    
    # Proper GH CLI setup
    - name: Install GitHub CLI
      run: |
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
        sudo apt update
        sudo apt install gh -y
        
    - name: Configure GH CLI
      run: |
        gh config set prompt disabled
        gh auth status || gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
      
    # Find latest successful features run
    - name: Get latest features run
      id: get_run
      run: |
        LATEST_RUN=$(gh run list -w "Feature Collection" --json databaseId,conclusion -q 'map(select(.conclusion == "success")) | .[0].databaseId')
        echo "run_id=$LATEST_RUN" >> $GITHUB_OUTPUT
        
    # Download features
    - name: Download features
      uses: actions/download-artifact@v4
      with:
        name: aqi-features-${{ steps.get_run.outputs.run_id }}
        path: data/
        
    - name: Train model
      run: python scripts/train_model.py
      
    - name: Upload model
      uses: actions/upload-artifact@v4
      with:
        name: aqi-model-${{ github.run_number }}
        path: models/aqi_model.json
