name: Model Training Pipeline

on:
  schedule:
    - cron: '0 0 * * *'  # Daily
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    # CHANGED FROM v3 TO v4
    - name: Download features
      uses: actions/download-artifact@v4  # Updated version
      with:
        name: aqi-features
        path: data/

    - name: Train model
      run: python scripts/train_model.py
      
    # CHANGED FROM v3 TO v4  
    - name: Upload model
      uses: actions/upload-artifact@v4  # Updated version
      with:
        name: aqi-model
        path: models/aqi_model.json
