name: Model Training
on:
  schedule:
    - cron: '30 * * * *'  # Runs at :30 past every hour
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - uses: actions/checkout@v4
    
    # Download using the simple name pattern
    - name: Download features
      uses: actions/download-artifact@v4
      with:
        name: aqi-features
        path: data/
        
    # Fallback to list all artifacts if needed
    - name: Alternative download (if previous failed)
      if: failure() && steps.download-features.conclusion == 'failure'
      run: |
        echo "Trying alternative download method..."
        ARTIFACT_ID=$(gh api repos/${{ github.repository }}/actions/artifacts --jq '.artifacts[] | select(.name == "aqi-features") | .id')
        gh run download $ARTIFACT_ID -n "aqi-features" -D data/
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Verify download
      run: |
        if [ ! -f data/hourly_features.csv ]; then
          echo "::error::Feature file not found after all attempts!"
          echo "Contents of data/:"
          ls -la data/
          exit 1
        fi
        
    - name: Train model
      run: python scripts/train_model.py
      
    - name: Upload model
      uses: actions/upload-artifact@v4
      with:
        name: aqi-model-${{ github.run_number }}
        path: models/aqi_model.json
