name: Model Training
on:
  schedule:
    - cron: '30 * * * *'  # Runs at :30 past every hour
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install xgboost scikit-learn pandas numpy joblib
        pip list
        
    - name: Download features
      uses: actions/download-artifact@v4
      with:
        name: aqi-features
        path: data/
        
    - name: Verify features
      run: |
        if [ ! -f data/hourly_features.csv ]; then
          echo "::error::Feature file missing!"
          exit 1
        fi
        echo "Found $(wc -l < data/hourly_features.csv) records"
        
    - name: Create models directory
      run: mkdir -p models
      
    - name: Train model
      run: python scripts/train_model.py
      
    - name: Verify model
      run: |
        echo "Model files:"
        ls -lh models/
        python -c "import xgboost; print('XGBoost version:', xgboost.__version__)"
        
    - name: Upload model
      uses: actions/upload-artifact@v4
      with:
        name: aqi-model
        path: models/
        retention-days: 7
